[build]
  publish = "public"
  command = "yarn build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"



[[redirects]]
from = "/144/"
to = "/posts/20200224180513"
status = 301
force = true
[[redirects]]
from = "/270/"
to = "/posts/20200224190207"
status = 301
force = true
[[redirects]]
from = "/379/"
to = "/posts/20200224191133"
status = 301
force = true
[[redirects]]
from = "/407/"
to = "/posts/20200224192543"
status = 301
force = true
[[redirects]]
from = "/590/"
to = "/posts/20200225141249"
status = 301
force = true
[[redirects]]
from = "/596/"
to = "/posts/20200225142032"
status = 301
force = true
[[redirects]]
from = "/606/"
to = "/posts/20200225142401"
status = 301
force = true
[[redirects]]
from = "/624/"
to = "/posts/20200226175317"
status = 301
force = true
[[redirects]]
from = "/628/"
to = "/posts/20200226180416"
status = 301
force = true
[[redirects]]
from = "/630/"
to = "/posts/20200228124232"
status = 301
force = true
[[redirects]]
from = "/633/"
to = "/posts/20200228150223"
status = 301
force = true
[[redirects]]
from = "/635/"
to = "/posts/20200228155013"
status = 301
force = true
[[redirects]]
from = "/639/"
to = "/posts/20200228160544"
status = 301
force = true
[[redirects]]
from = "/641/"
to = "/posts/20200228161552"
status = 301
force = true
[[redirects]]
from = "/710/"
to = "/posts/20200228162147"
status = 301
force = true
[[redirects]]
from = "/777/"
to = "/posts/20200228164044"
status = 301
force = true
[[redirects]]
from = "/799/"
to = "/posts/20200228164918"
status = 301
force = true
[[redirects]]
from = "/886/"
to = "/posts/20200228173514"
status = 301
force = true
[[redirects]]
from = "/904/"
to = "/posts/20200228174022"
status = 301
force = true
[[redirects]]
from = "/926/"
to = "/posts/20200228175104"
status = 301
force = true
[[redirects]]
from = "/947/"
to = "/posts/20200228180254"
status = 301
force = true
[[redirects]]
from = "/912/"
to = "/posts/20200228180733"
status = 301
force = true
[[redirects]]
from = "/953/"
to = "/posts/20200228182137"
status = 301
force = true
[[redirects]]
from = "/991/"
to = "/posts/20200228182555"
status = 301
force = true
[[redirects]]
from = "/997/"
to = "/posts/20200228183239"
status = 301
force = true
[[redirects]]
from = "/1010/"
to = "/posts/20200228183507"
status = 301
force = true
[[redirects]]
from = "/1017/"
to = "/posts/20200228184408"
status = 301
force = true
[[redirects]]
from = "/1029/"
to = "/posts/20200228184817"
status = 301
force = true
[[redirects]]
from = "/1046/"
to = "/posts/20200228185928"
status = 301
force = true
[[redirects]]
from = "/1124/"
to = "/posts/20200229074818"
status = 301
force = true
[[redirects]]
from = "/1139/"
to = "/posts/20200229075503"
status = 301
force = true
[[redirects]]
from = "/1111/"
to = "/posts/20200229081221"
status = 301
force = true
[[redirects]]
from = "/1156/"
to = "/posts/20200229082605"
status = 301
force = true
[[redirects]]
from = "/1192/"
to = "/posts/20200229083842"
status = 301
force = true
[[redirects]]
from = "/1218/"
to = "/posts/20200229085032"
status = 301
force = true
[[redirects]]
from = "/1268/"
to = "/posts/20200229090229"
status = 301
force = true
[[redirects]]
from = "https://codelabo.netlify.com/*"
to = "https://codelabo.com/:splat"
status = 301
force = true
[[redirects]]
from = "/posts/*/"
to = "/posts/:splat"
status = 301
force = true
[[redirects]]
from = "/pages/*/"
to = "/pages/:splat"
status = 301
force = true